### ISSUE TITLE
Can futuapi code work with pyinstaller

### ISSUE THREAD

**Issue by elise10583** [FutunnOpen/py-futu-api#105]
Hi
I have created a few python script to run the futuapi with some trading algorithm.
However, when I try to create the exe using pyinstaller, I am getting this error when running the exe.
'OpenQuoteContext' is not defined

I had following your instruction in https://openapi.futunn.com/futu-api-doc/en/qa/other.html#5019. 
By copying the .py files in the /path/futu/commen/pb folder to the /dist

and I am still getting the following error after rerunning the pyinstaller.

C:\Users\ChiWa\PycharmProjects\TradingProject\dist\5Warrant>5Warrant.exe
Traceback (most recent call last):
  File "5Warrant.py", line 22, in <module>
NameError: name 'OpenQuoteContext' is not defined
[16824] Failed to execute script '5Warrant' due to unhandled exception!

My Futu location is in C:\Users\ChiWa\PycharmProjects\TradingProject\venv\Lib\site-packages\futu

I did not see the pyinstaller create a folder futu in C:\Users\ChiWa\PycharmProjects\TradingProject\dist\5Warrant, while it did create a folder for pandas, numfy, etc.  

Please help and feel free to let me know if additional info is needed.
Thank you.

Thanks,
Elise

**Comment by elise10583** [comment]
I had hard code the path for the venv and I am getting this error message now:

C:\Users\ChiWa>C:\Users\ChiWa\PycharmProjects\TradingProject\dist\5Warrant\5Warrant.exe
Traceback (most recent call last):
  File "5Warrant.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\__init__.py", line 100, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\quote\open_quote_context.py", line 10, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\common\open_context_base.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\common\utils.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\common\conn_mng.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\common\constant.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "futu\common\pb\Qot_GetCodeChange_pb2.py", line 17, in <module>
ModuleNotFoundError: No module named 'Common_pb2'
[5024] Failed to execute script '5Warrant' due to unhandled exception!

**Comment by elise10583** [comment]
It seems to have something to do the virtual environment.

**Comment by elise10583** [comment]
Do I need to put the pyinstaller in the venv?
