### ISSUE TITLE
[JAVA] dylib file 在 macosx 會出現 code signature invalid

### ISSUE THREAD

**Issue by hungchai** [FutunnOpen/py-futu-api#45]
```	
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib, 9): no suitable image found.  Did find:
	/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib: code signature invalid for '/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib'

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 57 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib, 9): no suitable image found.  Did find:
	/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib: code signature invalid for '/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib'

	/Users/.../GIT/futu-open-api/libFTAPIChannel.dylib: stat() failed with errno=1
```

**Comment by FutunnOpen** [comment]
你好，可加qq群108534288联系管理员解决。
